[package]
name = "hogwild"
version = "0.6.0"
edition = "2018"
authors = ["Daniël de Kok <me@danieldk.eu>"]
description = "Data types for hogwild SGD"
documentation = "https://docs.rs/hogwild/"
homepage = "https://finalfusion.github.io/finalfrontier"
repository = "https://github.com/finalfusion/finalfrontier.git"
license = "BlueOak-1.0.0"

[dependencies]
ndarray = "0.12"
